# Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: c384cfd0-59b0-4989-9d89-da24ab34c471

# Allow WMF5
os: WMF 5

# Skip on updates to the README
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /udpated readme.*|update.readme.*s/

build: false

# Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1
